capstone-master/learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('user_list/', views.user_list, name='userlist'),
    path('store_transaction/', views.store_transaction, name='store_transaction'),
]

capstone-master/learning_users/learning_users/urls.py
from django.urls import path, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]
from django.urls import path, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

capstone-master/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.conf import settings


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        
        if not email:
            raise ValueError('The Email field must be set')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    # Any additional fields or modifications you need
    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        swappable = 'AUTH_USER_MODEL'
        default_related_name = 'basic_app_users'

    
class UserProfileInfo(models.Model):
    profile_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    coin_balance = models.FloatField(default=0.0)
    point_balance = models.FloatField(default=0.0)

    def __str__(self):
        return self.user.email



class Transaction(models.Model):
    transactionID = models.AutoField(primary_key=True)
    recipient = models.ForeignKey(User, on_delete=models.CASCADE)
    points = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.transactionID)

capstone-master/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserProfileInfo

User = get_user_model()

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = UserProfileInfo
        fields = ('first_name', 'last_name', 'confirm_password')
        widgets = {
            'password': forms.PasswordInput(),
        }

capstone-master/learning_users/basic_app/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from .models import User, UserProfileInfo,Transaction


def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in. Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
            messages.success(request, 'Registration successful. Please log in.')
            return redirect('basic_app:user_login')
        else:
            messages.error(request, 'Registration failed. Please correct the errors.')
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


@csrf_protect
def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)

        if user:
            # Check if the account is active
            if user.is_active:
                # Log the user in.
                login(request, user)
                # Send the user back to some page.
                # In this case their homepage.
                return render(request, 'basic_app/dashboard.html', {})
            else:
                # If the account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used email: {} and password: {}".format(email, password))
            return HttpResponse("Invalid login details supplied." + email + " " + password)

    else:
        # Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})


@login_required
def dashboard(request):
    try:
        profile = UserProfileInfo.objects.get(user_id=request.user)
        coin_balance = profile.coin_balance
        point_balance = profile.point_balance
    except UserProfileInfo.DoesNotExist:
        coin_balance = 0.0
        point_balance = 0.0

    context = {
        'coin_balance': coin_balance,
        'point_balance': point_balance
    }

    return render(request, 'basic_app/dashboard.html', context)


@login_required
def user_list(request):
    if request.method == 'POST':
        recipient_id = request.POST.get('recipient')
        points = float(request.POST.get('points'))

        try:
            user = get_user_model().objects.get(id=recipient_id)
            recipient_profile = UserProfileInfo.objects.get(user_id=user.id)
            recipient_profile.point_balance += points
            recipient_profile.save()

            # Create a record of the points awarded
            transaction = Transaction.objects.create(recipient=user, points=points)
            # Perform any additional actions related to the transaction

            # Fetch the updated user list
            users = UserProfileInfo.objects.all()
            user_data = []
            for user in users:
                user_data.append({
                    'email': user.user.email,
                    'first_name': user.first_name,
                    'last_name': user.last_name,
                    'point_balance': user.point_balance,
                })

            # Return the updated user list as JSON response
            return JsonResponse({'users': user_data})

        except (get_user_model().DoesNotExist, UserProfileInfo.DoesNotExist):
            # Handle the case when the user or recipient profile does not exist
            pass
    transactions = Transaction.objects.all()
    users = UserProfileInfo.objects.all()
    context = {
        'users': users,
        'transactions': transactions
    }
    return render(request, 'basic_app/user_list.html', context)

def store_transaction(request):
    if request.method == 'POST' and request.is_ajax():
        recipient = request.POST.get('recipient')
        points = float(request.POST.get('points'))
        date = request.POST.get('date')
        time = request.POST.get('time')

        # Update the recipient's point balance in the database
        user = User.objects.get(email=recipient)
        user.point_balance += points
        user.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request'})

capstone-master/learning_users/templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Wallet</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/styleBASE.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/title.png' %}"/>
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- Bootstrap core JavaScript -->
    <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
    <!-- Font Awesome JS -->    
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>  
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>    
    {% block headerinclude %}
    {% endblock %}
</head>
<!-- Style -->
<style>
  .bg-custom-color {
    background-color: #FECC00;
    /* Add any additional styles you want */
  }

  .active-link {
    color: #9C7B16; /* Change this color to your desired active link color */
  }

  /* Add styles for links */
  .sidebar-link {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 10px 20px;
    margin-bottom: 10px;
    border-radius: 5px;
    transition: background-color 0.3s ease;
  }

  /* Add spacing between links */
  .list-group-item:not(:valid) {
    margin-left: 20px;
    margin-bottom: 10px;
    max-width: 80%;
    border-radius: 15px;
    background-color: #f8f9fa;

  }


  
   /* .container-fluid{
      background-color: #f8f9fa;
     **/

  


</style>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-custom-color border-right" id="sidebar-wrapper">
            <div class="sidebar-heading text-center">
                <img src="{% static 'img/btitle.png' %}" width="110" height="100" class="d-inline-block align-top" alt="">
                <br>Wallet
            </div>
            <div class="list-group list-group-flush">
              {% if user.is_authenticated %}
                  <a href="{% url 'basic_app:dashboard' %}" class="list-group-item list-group-item-action sidebar-link {% if 'dashboard' in request.path %}active-link{% endif %}">Dashboard</a>
                  <a href="{% url 'basic_app:dashboard' %}" class="list-group-item list-group-item-action sidebar-link {% if 'dashboard' in request.path %}active-link{% endif %}">Requests</a>
                  <a href="{% url 'basic_app:userlist' %}" class="list-group-item list-group-item-action sidebar-link {% if 'userlist' in request.path %}active-link{% endif %}">Users</a>
                  <a href="{% url 'logout' %}" class="list-group-item list-group-item-action sidebar-link mt-auto {% if 'logout' in request.path %}active-link{% endif %}">Logout</a>
              {% else %}
              <a href="/basic_app/user_login/" class="list-group-item list-group-item-action sidebar-link"
              onmouseover="this.style.backgroundColor='#f5f5f5'"
              onmouseenter="this.insertAdjacentHTML('beforebegin', '<span class=\'highlight-box\'></span>')"
              onmouseleave="this.previousSibling.remove()">
              Login
           </a>
                  <a href="{% url 'basic_app:register' %}" class="list-group-item list-group-item-action sidebar-link {% if 'register' in request.path %}active-link{% endif %}">Register</a>
              {% endif %}
          </div>
          
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper", style="background-color: #f8f9fa;">
          <nav class="navbar navbar-light" style="background-color: rgba(255, 255, 255, 0.8);">
            <!-- Navbar content -->
          
                <button class="navbar-toggler" type="button" id="menu-toggle">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </nav>
            <div class="container-fluid">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Custom scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
</body>
</html>

capstone-master/learning_users/templates/basic_app/dashboard.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
<!DOCTYPE html>
<html>
<head>
    
</head>
<body>
<div class="container custom-container">
       <div class="jumbotron">
    <h1>User Dashboard</h1>
<p>Welcome, {{ request.user.email }}!</p>
<p>Your Balance: {{ request.user.userprofileinfo.balance }}</p>
<table>
    <tr>
        <th>User</th>
        <th>Balance</th>
    </tr>
    {% for profile in profiles %}
    <tr>
        <td>{{ profile.user.email }}</td>
        <td>{{ profile.point_balance }}</td>
    </tr>
    {% endfor %}
</table>
</div>
</div>
</body>
</html>
{% endblock %}

capstone-master/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>WALLET SYSTEM</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.firstname }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

capstone-master/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<style>
   #page-content-wrapper {
    background: url("{% static 'img/basebg.PNG' %}") no-repeat;
    background-size: cover;
    /* Add any other styles you need for #page-content-wrapper */
  }

  .custom-container {
    /* Your container styles */
    display: flex;
    justify-content: center;
  }

  .jumbotron {
  background-color: rgba(33, 37, 41, 0.7); /* Darker background color */
  color: #ffffff; /* Light text color */
  /* Other styles for the jumbotron */
  margin: 0 auto;
}

  

  .custom-container {
    max-width: 800px;
    margin: 0 auto;
    margin-top: 0.3in;
    padding-left: 150px;
  }
  h1 {
    color: #9C7B16;
    margin-bottom: 20px;
  }
  .regbtn {
    margin-top: 1cm;
    text-align: center;
    margin-bottom: -1cm;
  }
  .form-group {
    margin-bottom: 20px;
  }
  .form-label {
    font-weight: bold;
  }
  .form-control {
    width: 100%;
    height: 40px;
    border-radius: 10px;
  }
  .btn-primary {
    width: 500px;
    background-color: #9C7B16;
    border-radius: 50px;
    padding: 10px 20px;
  }
  a:hover, a:active, a:link, a:visited {
    color: #9C7B16;
  }
  .logo {
    width: 110px;
    height: 100px;
    margin-bottom: 20px;
  }
</style>

<div class="container custom-container">
  <div class="jumbotron">
    <div style="display: flex; justify-content: center;">
      <div style="display: flex; justify-content: center;">
        <img src="{% static 'img/title.png' %}" alt="Logo" class="logo" style="width: 80%; max-width: 800px; margin-top: 20px; height: auto;">
      </div>
      
    </div>    
    
    <center>
      <h1 style="font-family: 'Arial', sans-serif;">Points and Coins</h1>
   
    
    <h6>Please fill in the details of your account.</h6>
  </center>
    <form id="login-form" method="post" action="{% url 'basic_app:user_login' %}">
      {% csrf_token %}
      <div class="form-group">
        
        <div class="form-group">
          <label class="form-label" for="email">Email<span class="required-field">:</span>*</label>
          <input class="form-control" type="email" name="email" placeholder="Enter your email" id="id_email" required>
          <span id="email-error" class="error-message"></span>
          
        </div>
        <div class="form-group">
          <label class="form-label" for="password">Password<span class="required-field">:</span>*</label>
          <input class="form-control" type="password" name="password" placeholder="Enter your password" id="id_password" required>
          <span id="password-error" class="error-message"></span>
        </div>
        
        
        
        
      <div class="regbtn">
        <input class="btn btn-primary" type="submit" value="Login">
      </div>
    </form>
    <br><br>
      <p class="login-link" style="text-align: center; color: #ffff;">Don't have an account? <a href="{% url 'basic_app:register' %}">Register</a></p>
    </div>
    
  </div>
</div>

<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  function validateForm() {
    var email = document.getElementById("id_email").value;
    var password = document.getElementById("id_password").value;
    var emailErrorElement = document.getElementById("email-error");
    var passwordErrorElement = document.getElementById("password-error");
    var emailPattern = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

    if (!emailPattern.test(email)) {
      emailErrorElement.innerHTML = "Invalid email address";
      return false;
    } else {
      emailErrorElement.innerHTML = "";
    }

    if (password === "") {
      passwordErrorElement.innerHTML = "Password is required";
      return false;
    } else {
      passwordErrorElement.innerHTML = "";
    }

    return true;
  }
</script> -->


{% endblock %}

capstone-master/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
<style>

#page-content-wrapper {
    background: url("{% static 'img/basebg.PNG' %}") no-repeat;
    background-size: cover;
    /* Add any other styles you need for #page-content-wrapper */
  }

  .custom-container {
    /* Your container styles */
    display: flex;
    justify-content: center;
  }

  .jumbotron {
  background-color: rgba(33, 37, 41, 0.7); /* Darker background color */
  color: #ffffff; /* Light text color */
  /* Other styles for the jumbotron */
  margin: 0 auto;
}
  .custom-container {
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
    margin-top: .3in;
    padding-left: 150px;
  }
  h4 {
    color: gray;
  }
  .regbtn {
    margin-top: 1cm;
    text-align: center;
    margin-bottom: -1cm;
  }
  .logo {
    width: 110px;
    height: 100px;
    margin-bottom: 20px;
  }
  .regform {
    padding-left: 50px;
  }
  .btn-primary {
    width: 500px;
    background-color: #9C7B16;
    border-radius: 50px;
    padding: 10px 20px;
  }
  .btn-primary:hover {
    background-color: #9C7B16;
  }
  .form-control {
    width: 100%; /* Extend the width to 100% */
    height: 40px;
    border-radius: 10px;
  }
  .login-link {
    display: block;
    margin-top: 10px;
    text-align: center;
  }
  .error-message {
    color: red;
  }
  a:hover, a:active,a:link,a:visited {
  color: #9C7B16;
}
</style>
<div class="container custom-container">
  <div class="jumbotron">
    <center>
    <img src="/static/img/title.png" alt="Logo" class="logo" style="width: 80%; max-width: 800px; margin-top: 20px; height: auto;">
  
    <div class="regform">
      {% if registered %}
      <h1>Thank you for registering!</h1>
      {% else %}
      <h1 style="font-family: 'Arial', sans-serif; color: #9c7b16;">Points and Coins</h1>

      <h6 style="font-family: 'Arial', sans-serif; color: #ffffff;">Come and join us! Register your account.</h6>
    </center>
      <form id="login-form" method="post" action="{% url 'basic_app:user_login' %}">
  {% csrf_token %}
  <div class="form-group">
    <label class="form-label" for="first_name">First Name<span class="required-field">:</span></label>
    <input class="form-control rounded" type="text" name="first_name" placeholder="Enter your first name" id="id_first_name" required>
  </div>
  <div class="form-group">
    <label class="form-label" for="last_name">Last Name<span class="required-field">:</span></label>
    <input class="form-control rounded" type="text" name="last_name" placeholder="Enter your last name" id="id_last_name" required>
  </div>
  <div class="form-group">
    <label class="form-label" for="email">Email<span class="required-field">:</span></label>
    <input class="form-control rounded" type="email" name="email" placeholder="Enter your email" id="id_email" required>
    <p id="email-error" class="error-message"></p>
  </div>
  <div class="form-group">
    <label class="form-label" for="password">Password<span class="required-field">:</span></label>
    <input class="form-control rounded" type="password" name="password" placeholder="Enter your password" id="id_password" required>
  </div>
  <div class="form-group">
    <label class="form-label" for="confirm_password">Confirm Password<span class="required-field">:</span></label>
    <input class="form-control rounded" type="password" name="confirm_password" placeholder="Confirm your password" id="id_confirm_password" required>
    <p id="password-error" class="error-message"></p>
  </div>
</form>

        <div class="regbtn">
          <input type="submit" name="" value="Register" class="btn btn-primary">
        </div>
      </form><br><br>
      <p class="login-link">Already have an account? <a href="{% url 'basic_app:user_login' %}">Log in</a></p>
    </div>
    {% endif %}
  </div>
</div>
<script>
  function validateForm() {
    var email = document.getElementById("id_email").value;
    var password = document.getElementById("id_password").value;
    var confirmPassword = document.getElementById("id_confirm_password").value;
    var emailErrorElement = document.getElementById("email-error");
    var passwordErrorElement = document.getElementById("password-error");
    var emailPattern = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

    if (!emailPattern.test(email)) {
      emailErrorElement.innerHTML = "Invalid email address";
      return false;
    } else {
      emailErrorElement.innerHTML = "";
    }

    if (password !== confirmPassword) {
      passwordErrorElement.innerHTML = "Passwords do not match";
      return false;
    } else {
      passwordErrorElement.innerHTML = "";
    }

    return true;
  }
</script>
{% endblock %}